name: Continuous deployment

on:
  push:
    branches: [main]
    paths-ignore:
      - '.devcontainer/**'
      - '.github/**'

jobs:
  call-workflow:
    uses: compulim/workflows/.github/workflows/continuous-deployment.yml@main
    with:
      package-name: use-read-alert
