name: Continuous deployment

on:
  push:
    branches: [main]
    paths-ignore:
      - '.devcontainer/**'
      - '.github/**'
  workflow_dispatch: {}

jobs:
  call-workflow:
    permissions:
      pages: write
      id-token: write
    uses: compulim/workflows/.github/workflows/continuous-deployment.yml@main
    with:
      dry-run: ${{ github.event_name == 'workflow_dispatch' }}
      package-name: use-read-alert
